config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'

  resources :shoes
  resources :carts
  get 'login/index'
  get 'contacts/index'
  get 'blog/index'
  get 'about/index'
  get 'home/index'
  

    
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :shoe
  belongs_to :user
  belongs_to :order

  validates :size, :quantity, presence: true
end
  

app/models/category.rb
class Category < ApplicationRecord
   has_many :shoes

   validates :name, :active, presence: true

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :carts     #--i have written
  has_many :shoes, through: :carts

  validates :shoe_total,:discount,:final_total, numericality: true
end

app/models/shoe.rb
class Shoe < ApplicationRecord
  belongs_to :category
  has_many :carts
  has_many :orders, through: :carts

  validates :brand, :category, :size, :active, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,:trackable,
         :recoverable, :rememberable, :validatable
 
 
  has_many :carts, dependent: :destroy
  has_many :orders

  validates :email, presence: true, format: {with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create}
  validates :name,:password, :address, presence: true
  validates :mobile, length: {maximum:10}

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def index
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: %i[ show edit update destroy ]

  # GET /carts or /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1 or /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts or /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to cart_url(@cart), notice: "Cart was successfully created." }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1 or /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to cart_url(@cart), notice: "Cart was successfully updated." }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1 or /carts/1.json
  def destroy
    @cart.destroy

    respond_to do |format|
      format.html { redirect_to carts_url, notice: "Cart was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cart_params
      params.require(:cart).permit(:shoe_id, :order_id, :user_id, :size, :quantity)
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
  end
end

app/controllers/shoes_controller.rb
class ShoesController < ApplicationController
  before_action :authenticate_user!, :set_shoe, only: %i[ show edit update destroy ]

  # GET /shoes or /shoes.json
  def index
    @shoes = Shoe.all
  end

  # GET /shoes/1 or /shoes/1.json
  def show
  end

  # GET /shoes/new
  def new
    @shoe = Shoe.new
  end

  # GET /shoes/1/edit
  def edit
  end

  # POST /shoes or /shoes.json
  def create
    @shoe = Shoe.new(shoe_params)

    respond_to do |format|
      if @shoe.save
        format.html { redirect_to shoe_url(@shoe), notice: "Shoe was successfully created." }
        format.json { render :show, status: :created, location: @shoe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @shoe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shoes/1 or /shoes/1.json
  def update
    respond_to do |format|
      if @shoe.update(shoe_params)
        format.html { redirect_to shoe_url(@shoe), notice: "Shoe was successfully updated." }
        format.json { render :show, status: :ok, location: @shoe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @shoe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shoes/1 or /shoes/1.json
  def destroy
    @shoe.destroy

    respond_to do |format|
      format.html { redirect_to shoes_url, notice: "Shoe was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shoe
      @shoe = Shoe.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shoe_params
      params.require(:shoe).permit(:category_id, :name, :brand, :size, :active)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/indices_helper.rb
module IndicesHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/shoes_helper.rb
module ShoesHelper
end

app/views/carts/_cart.html.erb
<div id="<%= dom_id cart %>" class='mt-5'>
	<div class="hero-wrap hero-bread" style="background-image: url(<%= asset_path 'bg_6.jpg'%>);">
      <div class="container ">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
          <div class="col-md-9 ftco-animate text-center">
          	<p class="breadcrumbs"><span class="mr-2"><%= link_to 'home', home_index_path %></span> <span>Cart</span></p>
            <h1 class="mb-0 bread">My Wishlist</h1>
          </div>
        </div>
      </div>
    </div>

    <section class="ftco-section ftco-cart ">
			<div class="container">
				<div class="row">
    			<div class="col-md-12 ftco-animate">
    				<div class="cart-list">
	    				
						<!-- wishlist tables -->

						<table class="table">
						    <thead class="thead-primary">
						      <tr class="text-center">
						        <th>&nbsp;</th>
						        <th>&nbsp;</th>
						        <th>Shoe</th>
						        <th>Price</th>
						        <th>Quantity</th>
						        <th>Total</th>
						      </tr>
						    </thead>
						    <tbody>
						      <tr class="text-center">
						        <td class="product-remove"><a href="#"><span class="ion-ios-close"></span></a></td>
						        
						        <td class="image-prod"><div class="img" style="background-image:url(<%= asset_path 'product-3.jpg' %>);"></div></td>
						        
						        <td class="product-name">
						        	<h3><%= cart.shoe.name%></h3>
						        	<p>Far far away, behind the word mountains, far from the countries</p>
						        </td>
						        
						        <td class="price">2500</td>
						        
						        <td class="quantity">
						        	<div class="input-group mb-3">
                       		 <span class= "quantity form-control input-number">
      			             	<p class="mt-3"><%= cart.quantity%></p>              
                       		 </span>
                        <%# <input type="text" name="quantity" class="quantity form-control input-number" min="1" max="100"> %>
					          	</div>
					          </td>
						        
						        <td class="total"><%= cart.order.final_total%></td>
						      </tr><!-- END TR-->

						      <tr class="text-center">
						        <td class="product-remove"><a href="#"><span class="ion-ios-close"></span></a></td>
						        
						        <td class="image-prod"><div class="img" style="background-image:url(<%= asset_path 'product-4.jpg'%>);"></div></td>
						        
						        <td class="product-name">
						        	<h3>Nike Free RN 2019 iD</h3>
						        	<p>Far far away, behind the word mountains, far from the countries</p>
						        </td>
						        
						        <td class="price">$15.70</td>
						        
						        <td class="quantity">
						        	<div class="input-group mb-3">
					             	<input type="text" name="quantity" class="quantity form-control input-number" value="1" min="1" max="100">
					          	</div>
					          </td>
						        
						        <td class="total">$15.70</td>
						      </tr><!-- END TR-->
						    </tbody>
						  </table>
					  </div>
    			</div>
    		</div>
    		
<!-- billing -->

			<div class="row justify-content-start">
    			<div class="col col-lg-5 col-md-6 mt-5 cart-wrap ftco-animate">
    				<div class="cart-total mb-3">
    					<h3>Cart Totals</h3>
    					<p class="d-flex">
    						<span>Subtotal</span>
    						<span><%= cart.order.shoe_total%></span>
    					</p>
    					<p class="d-flex">
    						<span>Delivery</span>
    						<span>$0.00</span>
    					</p>
    					<p class="d-flex">
    						<span>Discount</span>
    						<span><%= cart.order.discount%></span>
    					</p>
    					<hr>
    					<p class="d-flex total-price">
    						<span>Total</span>
    						<span><%= cart.order.final_total%></span>
    					</p>
    				</div>
    				<p class="text-center"><a href="checkout.html" class="btn btn-primary py-3 px-4">Proceed to Checkout</a></p>
    			</div>
    		</div>
			</div>
		</section>
</div>

app/views/carts/_form.html.erb
<section class="vh-100 mt-5">
    <div class="container text-center">
         <%= form_with(model: cart) do |form| %>
            <% if cart.errors.any? %>
                <div style="color: red">
                  <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

                  <ul>
                    <% cart.errors.each do |error| %>
                      <li><%= error.full_message %></li>
                    <% end %>
                  </ul>
                </div>
            <% end %>

            <div>
              <%= form.label :shoe, style: "display: block" %>
              <%= form.text_field :shoe_id %>
            </div>

            <div>
              <%= form.label :order, style: "display: block" %>
              <%= form.text_field :order_id %>
            </div>

            <div>
              <%= form.label :user, style: "display: block" %>
              <%= form.text_field :user_id %>
            </div>

            <div>
              <%= form.label :size, style: "display: block" %>
              <%= form.text_field :size %>
            </div>

            <div>
              <%= form.label :quantity, style: "display: block" %>
              <%= form.text_field :quantity %>
            </div>

            <div>
              <%= form.submit %>
            </div>
        <% end %>
    
    </div>
</section>

app/views/carts/edit.html.erb
<div class="container">
  <h1 class = "mt-5">Editing cart</h1>

    <%= render "form", cart: @cart %>

  <br>

  <div>
    <%= link_to "Show this cart", @cart %> |
    <%= link_to "Back to carts", carts_path %>
  </div>
</div>

app/views/carts/index.html.erb
<p style="color: green"><%= notice %></p>

<div id="cart">
      <div class="container mt-5">
      <h1><%= link_to "New cart", new_cart_path%></h1>
              
              <h2 class="display-4">Carts</h2>

          <table class="table table-striped table-dark mt-5">
                <thead>
                  <tr>
                    <th scope="col">Shoe</th>
                    <th scope="col">Order/discount</th>
                    <th scope="col">price</th>
                    <th scope="col">Size</th>
                    <th scope="col">Quantity</th>
                  </tr>
                </thead>

             <% @carts.each do |cart| %>

                <tbody>
                  <tr>
                    <th><%= cart.shoe.name%></th>
                    <td><%= cart.order.discount%></td>
                    <td><%= cart.order.final_total%></td>
                    <td><%= cart.shoe.size%></td>
                    <td><%= cart.quantity%></td>
                    <td><%= link_to "show cart", cart%></td>
                  </tr>
                </tbody>
                    
              <%#= render cart %>
              <%# <p> %>
                <%#= link_to "Show this cart", cart %>
              <%# </p> %>
          <% end %>
        </table>
    </div>
</div>
  

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render "form", cart: @cart %>

<br>

<div>
  <%= link_to "Back to carts", carts_path %>
</div>

app/views/carts/show.html.erb
<p style="color: green" class = "mt-5"><%= notice %></p>

  <%= render @cart %>

<div class="text-center mb-5">
  <%= link_to "Edit this cart", edit_cart_path(@cart) %> |
  <%= link_to "Back to carts", carts_path %>
  <%= button_to "Destroy this cart", @cart, method: :delete , class:"btn btn-secondary mt-3"%>
</div>

app/views/shoes/_form.html.erb
<%= form_with(model: shoe) do |form| %>
  <% if shoe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(shoe.errors.count, "error") %> prohibited this shoe from being saved:</h2>

      <ul>
        <% shoe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :category, style: "display: block" %>
    <%= form.text_field :category_id%>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :brand, style: "display: block" %>
    <%= form.text_field :brand %>
  </div>

  <div>
    <%= form.label :size, style: "display: block" %>
    <%= form.text_field :size %>
  </div>

  <div>
    <%= form.label :active, style: "display: block" %>
    <%= form.text_field :active %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/shoes/_shoe.html.erb
<div id="<%= dom_id shoe %>">
  <p>
    <strong>Category:</strong>
    <%= shoe.category %>
  </p>
                        
  <p>
    <strong>Name:</strong>
    <%= shoe.name %>
  </p>

  <p>
    <strong>Brand:</strong>
    <%= shoe.brand %>
  </p>

  <p>
    <strong>Size:</strong>
    <%= shoe.size %>
  </p>

  <p>
    <strong>Active:</strong>
    <%= shoe.active %>
  </p>

</div>

app/views/shoes/edit.html.erb
<h1>Editing shoe</h1>

<%= render "form", shoe: @shoe %>

<br>

<div>
  <%= link_to "Show this shoe", @shoe %> |
  <%= link_to "Back to shoes", shoes_path %>
</div>

app/views/shoes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Shoes</h1>

<div id="shoes">
  <% @shoes.each do |shoe| %>
    <%= render shoe %>
    <p>
      <%= link_to "Show this shoe", shoe %>
    </p>
  <% end %>
</div>

<%= link_to "New shoe", new_shoe_path %>

app/views/shoes/new.html.erb
<h1>New shoe</h1>

<%= render "form", shoe: @shoe %>

<br>

<div>
  <%= link_to "Back to shoes", shoes_path %>
</div>

app/views/shoes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @shoe %>

<div>
  <%= link_to "Edit this shoe", edit_shoe_path(@shoe) %> |
  <%= link_to "Back to shoes", shoes_path %>

  <%= button_to "Destroy this shoe", @shoe, method: :delete %>
</div>