config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'

  resources :shoes
  resources :carts
  get 'login/index'
  get 'contacts/index'
  get 'blog/index'
  get 'about/index'
  get 'home/index'
  

    
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :shoe
  belongs_to :user
  belongs_to :order

  validates :size, :quantity, presence: true
end
  

app/models/category.rb
class Category < ApplicationRecord
   has_many :shoes

   validates :name, :active, presence: true

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :carts     #--i have written
  has_many :shoes, through: :carts

  validates :shoe_total,:discount,:final_total, numericality: true
end

app/models/shoe.rb
class Shoe < ApplicationRecord
  belongs_to :category
  has_many :carts
  has_many :orders, through: :carts

  validates :brand, :category, :size, :active, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,:trackable,
         :recoverable, :rememberable, :validatable
 
 
  has_many :carts, dependent: :destroy
  has_many :orders

  validates :email, presence: true, format: {with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create}
  validates :name,:password, :address, presence: true
  validates :mobile, length: {maximum:10}

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def index
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: %i[ show edit update destroy ]

  # GET /carts or /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1 or /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts or /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to cart_url(@cart), notice: "Cart was successfully created." }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1 or /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to cart_url(@cart), notice: "Cart was successfully updated." }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1 or /carts/1.json
  def destroy
    @cart.destroy

    respond_to do |format|
      format.html { redirect_to carts_url, notice: "Cart was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cart_params
      params.require(:cart).permit(:shoe_id, :order_id, :user_id, :size, :quantity)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/indices_helper.rb
module IndicesHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/shoes_helper.rb
module ShoesHelper
end

app/views/layouts/_footer.html.erb
<!--*************** SECTION-7 *************-->
                                                  
    <section class="ftco-gallery">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-md-8 heading-section text-center mb-4 ftco-animate">
            <h2 class="mb-4">Follow Us On Instagram</h2>
            <p>
              Far far away, behind the word mountains, far from the countries
              Vokalia and Consonantia, there live the blind texts. Separated
              they live in
            </p>
          </div>
        </div>
      </div>
      <div class="container-fluid px-0">
        <div class="row no-gutters">
          <div class="col-md-4 col-lg-2 ftco-animate">
            <a
              href="images/gallery-1.jpg"
              class='gallery image-popup img d-flex align-items-center'
              style="background-image: url(<%= asset_path 'gallery-1.jpg'%>)"
            >
              <div
                class="icon mb-4 d-flex align-items-center justify-content-center"
              >
                <span class="icon-instagram"></span>
              </div>
            </a>
          </div>
          <div class="col-md-4 col-lg-2 ftco-animate">
            <a
              href="images/gallery-2.jpg"
              class="gallery image-popup img d-flex align-items-center"
              style="background-image: url(<%= asset_path 'gallery-2.jpg'%>)"
            >
              <div
                class="icon mb-4 d-flex align-items-center justify-content-center"
              >
                <span class="icon-instagram"></span>
              </div>
            </a>
          </div>
          <div class="col-md-4 col-lg-2 ftco-animate">
            <a
              href="images/gallery-3.jpg"
              class="gallery image-popup img d-flex align-items-center"
              style="background-image: url(<%= asset_path 'gallery-3.jpg'%>)"
            >
              <div
                class="icon mb-4 d-flex align-items-center justify-content-center"
              >
                <span class="icon-instagram"></span>
              </div>
            </a>
          </div>
          <div class="col-md-4 col-lg-2 ftco-animate">
            <a
              href="images/gallery-4.jpg"
              class="gallery image-popup img d-flex align-items-center"
              style="background-image: url(<%= asset_path 'gallery-4.jpg'%>)"
            >
              <div
                class="icon mb-4 d-flex align-items-center justify-content-center"
              >
                <span class="icon-instagram"></span>
              </div>
            </a>
          </div>
          <div class="col-md-4 col-lg-2 ftco-animate">
            <a
              href="images/gallery-5.jpg"
              class="gallery image-popup img d-flex align-items-center"
              style="background-image: url(<%= asset_path 'gallery-5.jpg'%>)"
            >
              <div
                class="icon mb-4 d-flex align-items-center justify-content-center"
              >
                <span class="icon-instagram"></span>
              </div>
            </a>
          </div>
          <div class="col-md-4 col-lg-2 ftco-animate">
            <a
              href="images/gallery-6.jpg"
              class="gallery image-popup img d-flex align-items-center"
              style="background-image: url(<%= asset_path 'gallery-6.jpg'%>)"
            >
              <div
                class="icon mb-4 d-flex align-items-center justify-content-center"
              >
                <span class="icon-instagram"></span>
              </div>
            </a>
          </div>
        </div>
      </div>
    </section>





 <!--************* FOOTER ***************-->

<footer class="ftco-footer ftco-section">
    <div class="container">
        <div class="row">
            <div class="mouse">
                <a href="#" class="mouse-icon">
                <div class="mouse-wheel">
                    <span class="ion-ios-arrow-up"></span>
                </div>
                </a>
            </div>
        </div>

            <%# minishop %>

        <div class="row mb-5">
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Minishop</h2>
                    <p>
                        Far far away, behind the word mountains, far from the countries
                        Vokalia and Consonantia.
                    </p>
                    <ul
                        class="ftco-footer-social list-unstyled float-md-left float-lft mt-5"
                    >
                        <li class="ftco-animate">
                        <a href="#"><span class="icon-twitter"></span></a>
                        </li>
                        <li class="ftco-animate">
                        <a href="#"><span class="icon-facebook"></span></a>
                        </li>
                        <li class="ftco-animate">
                        <a href="#"><span class="icon-instagram"></span></a>
                        </li>
                    </ul>
                </div>
            </div>
            
                <%# menu %>

            <div class="col-md">
                <div class="ftco-footer-widget mb-4 ml-md-5">
                    <h2 class="ftco-heading-2">Menu</h2>
                    <ul class="list-unstyled">
                        <li><a href="#" class="py-2 d-block">Shop</a></li>
                        <li><a href="#" class="py-2 d-block">About</a></li>
                        <li><a href="#" class="py-2 d-block">Journal</a></li>
                        <li><a href="#" class="py-2 d-block">Contact Us</a></li>
                    </ul>
                </div>
            </div>

            <%# help  %>

            <div class="col-md-4">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Help</h2>
                    <div class="d-flex">
                        <ul class="list-unstyled mr-l-5 pr-l-3 mr-4">
                            <li>
                                <a href="#" class="py-2 d-block">Shipping Information</a>
                            </li>
                            <li>
                                <a href="#" class="py-2 d-block">Returns &amp; Exchange</a>
                            </li>
                            <li>
                                <a href="#" class="py-2 d-block">Terms &amp; Conditions</a>
                            </li>
                            <li><a href="#" class="py-2 d-block">Privacy Policy</a></li>
                        </ul>
                        <ul class="list-unstyled">
                            <li><a href="#" class="py-2 d-block">FAQs</a></li>
                            <li><a href="#" class="py-2 d-block">Contact</a></li>
                        </ul>
                    </div>
                </div>
            </div>

                <%# hav a question %>

            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Have a Questions?</h2>
                    <div class="block-23 mb-3">
                        <ul>
                            <li>
                                <span class="icon icon-map-marker"></span>
                                <span class="text">203 Fake St. Mountain View, San Francisco, California,
                                USA</span>
                            </li>
                            <li>
                                <a href="#"><span class="icon icon-phone"></span>
                                <span class="text">+2 392 3929 210</span></a>                              
                            </li>
                            <li>
                                <a href="#"><span class="icon icon-envelope"></span>
                                <span class="text">info@yourdomain.com</span></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

                <%# copyrights %>

        <div class="row">
            <div class="col-md-12 text-center">
                <p>
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                Copyright &copy;
                <script>
                    document.write(new Date().getFullYear());
                </script>
                All rights reserved
                </p>
            </div>
        </div>
    </div>
</footer>

    <!-- loader -->

<div id="ftco-loader" class="show fullscreen">
    <svg class="circular" width="48px" height="48px">
        <circle
          class="path-bg"
          cx="24"
          cy="24"
          r="22"
          fill="none"
          stroke-width="4"
          stroke="#eeeeee"
        />
        <circle
          class="path"
          cx="24"
          cy="24"
          r="22"
          fill="none"
          stroke-width="4"
          stroke-miterlimit="10"
          stroke="#F96D00"
        />
    </svg>
</div>

app/views/layouts/_header.html.erb
<div class="py-1 bg-black">
    <div class="container">
        <div class="row no-gutters d-flex align-items-start align-items-center px-md-0">
            <div class="col-lg-12 d-block">
                <div class="row d-flex">
                    <div class="col-md pr-4 d-flex topper align-items-center">
                        <div class="icon mr-2 d-flex justify-content-center align-items-center">
                            <span class="icon-phone2"></span>
                        </div>
                        <span class="text">+91 8421370161</span>
                    </div>
                    <div class="col-md pr-4 d-flex topper align-items-center">
                        <div class="icon mr-2 d-flex justify-content-center align-items-center">
                            <span class="icon-paper-plane"></span>
                        </div>
                        <span class="text">tejas.raut@softices.com</span>
                    </div>
                    <div class="col-md-5 pr-4 d-flex topper align-items-center text-lg-right">
                        <span class="text">3-5 Business days delivery &amp; Free Returns</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

    <!-- 
    ----------------------
    navbar
    ----------------------
    -->

<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
    <div class="container">
        <a class="navbar-brand" href="index.html">Shoeshop</a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#ftco-nav"
          aria-controls="ftco-nav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="oi oi-menu"></span> Menu
        </button>

        <div class="col-sm-5 col-md-3 mt-3">
          <form action="#" class="form-group d-inline-flex">
            <input
              list="shoes"
              type="search"
              class="px-2"
              style="padding: 2px; width: 300px; border-radius: 8px;height: 35px; border: none;"
              placeholder="search"
            />
            <datalist id="shoes">
              <option><%= Category.first.name%></option>
              <option><%= Category.find(2).name %></option>
              <option><%= Category.last.name%></option>
            </datalist>
            <button
              class="btn btn-primary submit-search text-center"
              style="margin-left: 5px"
              type="submit"
            >
              <i class="icon-search"></i>
            </button>
          </form>
        </div>

        <div class="collapse navbar-collapse" id="ftco-nav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <%= link_to 'home', home_index_path,  class:'nav-link'%>
                    <%# <a href="index.html" class="nav-link">Home</a> %>
                </li>
                <li class="nav-item dropdown">
                <a
                    class="nav-link dropdown-toggle"
                    href="#"
                    id="dropdown04"
                    data-toggle="dropdown"
                    aria-haspopup="true"
                    aria-expanded="false"
                    >Catalog</a>
                <div class="dropdown-menu" aria-labelledby="dropdown04">
                    <%= link_to 'Shop', shoes_path, class:'dropdown-item' %>
                    <%# <a class="dropdown-item" href="shop.html">Shop</a> %>
                    <%#= link_to 'Single Product',single_product_index_path, class:'dropdown-item' %>
                    <a class="dropdown-item" href="product-single.html">Single Product</a>
                    <%= link_to 'Cart', carts_path, class:'dropdown-item' %>
                    <%# <a class="dropdown-item" href="cart.html">Cart</a> %>
                    <%#= link_to 'Checkout', checkout_index_path, class: 'dropdown-item' %>
                    <a class="dropdown-item" href="checkout.html">Checkout</a>
                </div>
                </li>
                <li class="nav-item">
                    <%= link_to 'about', about_index_path, class:'nav-link' %>
                    <%# <a href="about.html" class="nav-link">About</a> %>
                </li>
                <li class="nav-item">
                    <%= link_to 'blog', blog_index_path, class:'nav-link'%>
                    <%# <a href="blog.html" class="nav-link">Blog</a> %>
                </li>
                <li class="nav-item">
                    <%= link_to 'contacts', contacts_index_path, class:'nav-link' %>
                    <%# <a href="contact.html" class="nav-link">Contact</a> %>
                </li>
                <li class="nav-item">
                    <%= link_to 'log in', login_index_path, class:'nav-link' %>
                    <%# <a href="login.html" class="nav-link">Log in</a> %>
                </li>
                <li class="nav-item cta cta-colored mt-1">
                    <%= link_to 'cart', carts_path, class:'nav-link icon-shopping_cart' %>
                    <%# <a href="cart.html" class="nav-link">
                    <span class="icon-shopping_cart"></span>Cart[0]</a> %>
                </li>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shoeshop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link
      href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800"
      rel="stylesheet"
    />

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% if flash[:notice] %>
      <div class="notification is-success global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
    <div class="notification is-danger global-notification">
      <p class="alert"><%= alert %></p>
    </div>
    <% end %>
    
    <%= yield %>
    
    <%= render 'layouts/footer' %>
    <%= javascript_include_tag 'application', "data-turbo-track": "reload" %>
    <script src = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
  </body>
</html>